success_invite:
    pattern:  /invite/
    defaults: { _controller: SuccessInviteBundle:Invite:show }

success_invite_redirect:
    pattern:  /redirect/{service}/
    defaults: { _controller: SuccessInviteBundle:Invite:redirect }

success_invite_list:
    pattern:  /process-list/
    defaults: { _controller: SuccessInviteBundle:Invite:process }

success_invite_form:
    pattern:  /process-form/
    defaults: { _controller: SuccessInviteBundle:Invite:processForm }

