success_invite:
    pattern:  /invite/
    defaults: { _controller: SuccessInviteBundle:Invite:show }

success_invite_redirect_google:
    pattern:  /redirect/google/
    defaults: { _controller: SuccessInviteBundle:Invite:google }

success_invite_redirect_facebook:
    pattern:  /redirect/facebook/
    defaults: { _controller: SuccessInviteBundle:Invite:facebook }

success_invite_list:
    pattern:  /process-list/
    defaults: { _controller: SuccessInviteBundle:Invite:process }

success_invite_form:
    pattern:  /process-form/
    defaults: { _controller: SuccessInviteBundle:Invite:processForm }

